### PR TITLE
Feature/new apk release

### PR DESCRIPTION
**Pull request by benmaidel**
created new release, because the Script service moved from cob_android_script_server to cob_android_msgs.
Do only update to this version if you use the newest cob_android package

### CODE REVIEW

**Comment by NadiaHG** [comment]
Test on cob4-2: OK

**Comment by fmessmer** [comment]
@ipa-bnm
I merged #8 
Now this PR still adds a apk file...I'm unsure whether I should accept this one...maybe it will be gone after you pull in latest changes from ipa320 indigo_dev
Please test whether ipa320 indigo_dev contains the correct apk or whether this PR should be merged still...

**Comment by benmaidel** [comment]
this is the newest apk. only compatible with latest cob_android version. @ipa-nhg is cob4-2's robot account already updated to this version?

**Comment by NadiaHG** [comment]
Yes, the robot account is already updated, tested and working! :+1:

**Comment by fmessmer** [comment]
Has this been tested with the apk from this PR being installed on the tablet?
@ipa-nhg  please confirm and merge if it does and works...

**Comment by fmessmer** [comment]
@ipa-bnm @ipa-bnm 
Please confirm that latest apk from this branch is used on the tablet and **fully** working....

**Comment by benmaidel** [comment]
there is already a newer version of the app installed on the tablet. So this app is outdated. But i see no problem in merging this. If the newest Version is reported correct, i will create another PR

**Comment by floweisshardt** [comment]
I'll merge this.

@ipa-bnm: new tablet app version was tested succesfully on cob4-2: All OK. please open a new PR.

**Pull request merged**
