### PR TITLE
Feature/non blocking service calls

### PR DESCRIPTION
**Pull request by benmaidel**
this solves #4

### CODE REVIEW

**Comment by NadiaHG** [comment]
Test on cob4-2: OK

**Comment by fmessmer** [comment]
@ipa-bnm: Could you please merge with latest ipa320 indigo_dev and resolve merge conflict?

**Comment by benmaidel** [comment]
merged with ipa320/indigo_dev, automerge should work

**Comment by NadiaHG** [comment]
LGTM

**Pull request merged**
