### PR TITLE
do not use sub folder for installed scripts

### PR DESCRIPTION
**Pull request by floweisshardt**
follow-up PR from #28 and adressing @ipa-mdl's suggestion

### CODE REVIEW

**Comment by fmessmer** [comment]
the problem is that the script is also installed in the setup.py....which leads to file-exists errors sometimes...which is why I removed the install tag recently...maybe I should have removed it feom setup.py instead...

greetings from civilization...trenta, slovenia...

**Comment by floweisshardt** [comment]
greeting back @ipa-fxm: hope you enjoy your trip and miss the robots already :-)

so what's you suggestion? merge or remove from setup.py?

**Comment by mathias-luedtke** [comment]
> merge or remove from setup.py?

both!

**Comment by benmaidel** [comment]
added PR to fmw's patch branch https://github.com/ipa320/cob_android/pull/30

**Review by benmaidel — APPROVED** [review]

**Comment by floweisshardt** [comment]
FR: OK

**Pull request merged**
